### ISSUE TITLE
PR for ss3 branch

### ISSUE THREAD

**Issue by sanderha** [silverstripe-terraformers/gridfield-rich-filter-header#1]
Hello,

Great module. We've recently used it for a ss3 project and for that we had to create a fork and a ss3 branch. Would you mind creating a branch for a ss3 version of this module? That way we can do a PR to that branch.

Our ss3 branch can be found here https://github.com/rasmniel/gridfield-rich-filter-header/tree/ss3

**Comment by mfendeksilverstripe** [comment]
@sanderha 

Hi, 

thank you for your contribution :). I've created a SS3 branch here:

https://github.com/silverstripe-terraformers/gridfield-rich-filter-header/tree/SS3

Feel free to create a PR on that branch.

**Comment by sanderha** [comment]
Thanks!
