### ISSUE TITLE
Filtering many_many realtions does not work

### ISSUE THREAD

**Issue by schrattenholz** [silverstripe-terraformers/gridfield-rich-filter-header#12]
Hi,
this is a great component, which really does rise the value of silverstripe-cms.
Sadly I can not get it working with a many_many relation.
I tried your FILTER_MANY_MANY_RELATION-example code, but no dropdown provided. The screenshots does not belong to the codesnippet.
Can you provide a full-example for a many_many-relation?

thanks in advance

**Comment by mfendeksilverstripe** [comment]
Hi @tiefseh , thank you for raising this issue. Can you please add some more details so I can look into this? I would keen on having the following information:

* SilverStripe framework version you are using
* Code snippets of your ORM setup (model1, model2 and their many many relationship definition)
* Code snippet of your CMS fields setup where you're using the RichFilter header

Thanks.

**Comment by mfendeksilverstripe** [comment]
Closing this as this issue has become stale (more feedback was needed)
