### ISSUE TITLE
Component modifies all model admins

### ISSUE THREAD

**Issue by jacobaarnold** [silverstripe-terraformers/gridfield-rich-filter-header#15]
It wasn't clear from the documentation, but in Silverstripe 4.10, just installing this component seems to change the default filtering of all model admins from a search field above the Gridfield to separate header text fields. Is this intentional? Is there a way to control which model admins are affected?

**Comment by mfendeksilverstripe** [comment]
Fixed in https://github.com/silverstripe-terraformers/gridfield-rich-filter-header/pull/16 , released in `3.0.0`
