### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by phptek** [silverstripe-terraformers/gridfield-rich-filter-header#18]
I've made some mods to one of the class files of this module and included in my own app's source code.  I'd like to ensure proper attribution is made to the original authors and to the license, but this package doesn't comprise the standard metafiles I'd expect to see in a Silverstripe module:

LICENCE.md
CONTRIBUTING.md
...etc

I think it would be beneficial to the maintainers if these metafiles were included in this project's source code.

**Comment by mfendeksilverstripe** [comment]
Fixed in https://github.com/silverstripe-terraformers/gridfield-rich-filter-header/pull/20
