### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by sanderha** [silverstripe-terraformers/gridfield-rich-filter-header#3]
Am I stupid, or is this module not on packagist.org (anymore)?

**Comment by chrispenny** [comment]
You're definitely not stupid - there is some weirdness going on.

Thank you for raising the ticket, we're checking it out.

**Comment by chrispenny** [comment]
Hopefully we're back up and running now:
https://packagist.org/packages/silverstripe-terraformers/gridfield-rich-filter-header

Please re-open this ticket if you're still having any troubles.
