### ISSUE TITLE
Search icon not visible

### ISSUE THREAD

**Issue by AljosaB** [silverstripe-terraformers/gridfield-rich-filter-header#4]
Since SS 4.3 search icon doesn't show up when page loads. It only gets visible after I sort any column. The problem is related to https://docs.silverstripe.org/en/4/changelogs/4.3.0/#using-legacy-gridfield-search-api and setting `useLegacyFilterHeader=true` solves the problem.

**Comment by mfendeksilverstripe** [comment]
Thanks for the heads up, will have a look at it next week.

**Comment by mfendeksilverstripe** [comment]
@AljosaB  Fixed in [Release 2.1.1](https://github.com/silverstripe-terraformers/gridfield-rich-filter-header/releases/tag/v2.1.1)
