### ISSUE TITLE
Add example for HasOne relation

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe-terraformers/gridfield-rich-filter-header#6]
This seems like an extremely versatile package! But all these data relations can get a bit complicated,.. and I have to admit I don't even manage to get a filter on a HasOne relationship working. Would you consider adding an example for that? 😊

Example: we have `Player` and `Team`, both simply have a 'Title'. But each Player also `has_one` Team 
(and Team `has_many` Players), and now I want to filter my list of Players by their Team, so I want to (partially) type the Title of the Team and then filter the Players down to those in that team.

It sounds simple to me but couldn't get it to work in half an hour, so gave up for now.

**Comment by mfendeksilverstripe** [comment]
Thanks for feedback, will have a look at this next week ;-)

**Comment by mfendeksilverstripe** [comment]
@JorisDebonnet Fixed in [Release 2.1.1](https://github.com/silverstripe-terraformers/gridfield-rich-filter-header/releases/tag/v2.1.1)
